# Generated by Django 5.2.14 on 2026-05-30 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_contact_custom_social_profiles_contact_discord_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='discord',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
