# Generated by Django 5.2.14 on 2026-06-02 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_contact_discord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='job_title',
            new_name='company',
        ),
    ]
