# Generated by Django 6.0.5 on 2026-06-07 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_add_company_is_workspace'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, default='en', max_length=10),
        ),
    ]
